export { default as Companion } from "./companion-login.jpg"
export { default as Burger } from "./burger-home.jpg"
export { default as Cookbook } from "./cookbook.jpg"
export { default as Weather } from "./weather.dashboard.jpg"
export { default as Planner } from "./workday.planner.gif"