export { default as Companion } from "./companion-login.jpg"
export { default as Burger } from "./burger-home.jpg"
export { default as Cookbook } from "./cookbook.jpg"
export { default as Weather } from "./weather.dashboard.jpg"
export { default as Planner } from "./workday.planner.gif"
export { default as Self } from "./self.jpg"
export { default as Budget } from "./budgetHome.png"
export { default as EmpDir } from "./empDirHome.png"